apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routedips.routedip.jcastillo2nd.info
spec:
  group: routedip.jcastillo2nd.info
  names:
    kind: RoutedIP
    listKind: RoutedIPList
    plural: routedips
    singular: routedip
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RoutedIP is the Schema for the routedips API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RoutedIPSpec defines the desired state of RoutedIP
          type: object
        status:
          description: RoutedIPStatus defines the observed state of RoutedIP
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
