apiVersion: routedipoperator.jcastillo2nd.com/v1alpha1
kind: RoutedIP
metadata:
  name: example-routedip
spec:
  className: digitalocean.com/floating-ip
  routedIP: 192.168.1.1
  serviceRef:
    namespace: default
    name: example-svc
