kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: routed-ip-operator
  namespace: routed-ip-operator
subjects:
- kind: ServiceAccount
  name: routed-ip-operator
  namespace: routed-ip-operator
roleRef:
  kind: ClusterRole
  name: routed-ip-operator
  apiGroup: rbac.authorization.k8s.io
